from math import *

print("Zero is", 4+4-4-4)
print("One is", 4/4*4/4)
print("Two is", (4*4)/4-sqrt(4))
print("Three is", (4*4-4)/4)
print("Four is", factorial(4)/4+sqrt(4)-4)
print("Five is", (4*4+4)/4)
print("Six is", factorial(4)/4+4-4)
print("Seven is", (factorial(4)/factorial(4)+4)+sqrt(4))
print("Eight is", 4*4-4-4)
print("Nine is", (factorial(4)-4)/4+4)
print("Ten is", 4*4-4-sqrt(4))
print("Eleven is", (factorial(4)+4)/4+4)
print("Twelve is", 4*4-sqrt(4)-sqrt(4))
print("Thirteen is", (factorial(4)+4-sqrt(4))/sqrt(4))
print("Fourteen is", 4*4+sqrt(4)-4)
print("Fifteen is", (factorial(4)+4+sqrt(4))/sqrt(4))
print("Sixteen is", (factorial(4)+factorial(4))/4+4)
print("Seventeen is", (factorial(4)+2)/2+4)
print("Eighteen is", factorial(4)-4-4+sqrt(4))
print("Nineteen is", (factorial(4)-4)-(4/4))
print("Twenty is", (factorial(4)*4)/4-4)